# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
deploymentLabel: cards
appName: cards

replicaCount: 1

image:
  repository: mais85/cards
  tag: latest

containerPort: 9001

service:
  type: LoadBalancer
  port: 9001
  targetPort: 9001

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
appname_enabled: true