# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
deploymentLabel: accounts
appName: accounts

replicaCount: 2

image:
  repository: mais85/accounts
  tag: latest

containerPort: 8081

service:
  type: NodePort
  port: 81
  targetPort: 8081

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
appname_enabled: true